# Generated by Django 2.2.6 on 2019-10-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=36)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=4)),
                ('payer_id_type', models.CharField(max_length=16)),
                ('party_id', models.CharField(max_length=16)),
                ('payer_message', models.CharField(max_length=32)),
                ('payee_note', models.CharField(max_length=32)),
                ('auth_status', models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'SUCCESSFUL')], default=0)),
                ('financial_transaction_id', models.CharField(max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
